steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stackpointcloud-206317/quarkus-getting-started', '-f',  'src/main/docker/Dockerfile.multistage', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stackpointcloud-206317/quarkus-getting-started']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'quarkus-getting-started', '--image', 'gcr.io/stackpointcloud-206317/quarkus-getting-started', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/stackpointcloud-206317/quarkus-getting-started